In [3]:
import os
import numpy as np
import urllib
# print message after packages imported successfully
print("import of packages successful")

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])  


#######################################
dat = np.loadtxt(fname = "zscore.txt") # no commas, no
dat # get the whole dataset
dat[1] #OR dat[1,] get row index 1
dat[1,1] # first item in row 1, column 1
dat[0:1, 0:3] # select the first row (0:1) and the first three columns (0:3)
new= dat[0:1, 0:30] # dat subset inclusive of the first row with all 30 column items
new.shape # get the dimensions of the new dataset


new*2.2 # Quick calculations using numpy!
np.mean(new) # get the mean!
np.min(new)
np.max(new)
#######################################
a = np.arange(0,60,5)
a = a.reshape(3,4)

print 'Original array is:'
print a
print '\n'

print 'Modified array is:'
for x in np.nditer(a):
   print x,


#######################################
# iterating over and manipulating a 
for x in np.nditer(dat, op_flags = ['readwrite']):
    rand= [-1,1]
    rand_choice= random.choice(rand)
    x[...] = 2*x
print 'Modified array is:'
print dat


# References:
#http://cs231n.github.io/python-numpy-tutorial/#numpy
#https://www.earthdatascience.org/courses/earth-analytics-bootcamp/numpy-arrays/manipulate-summarize-plot-numpy-arrays/

import of packages successful
<type 'numpy.ndarray'>
(3,)
(1, 2, 3)
[5 2 3]
[[1 2 3]
 [4 5 6]]
(1, 2, 4)
Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0 5 10 15 20 25 30 35 40 45 50 55

NameError: name 'random' is not defined